services:
  - type: web
    name: incentive-rfm-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=10000 --server.address=0.0.0.0"
    plan: free
    envVars:
      - key: GOOGLE_SHEET_URL
        value: https://docs.google.com/spreadsheets/d/1DliRCZiO33EOUdhHAWV1UBn180Rox7zWr0Oy0ikhtMQ
      - key: GOOGLE_SERVICE_ACCOUNT_FILE
        value: |
          {
            "type": "service_account",
            "project_id": "incentiverfv",
            "private_key_id": "4d29ff93fc46c80582f7680fe62536068e70986f",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCcbBHiB+UeHMFY\naYuLJLxb4KQ/4b0nf9LfYHkqs8PXjm7PrUlnW428e8TOJjmB8/nqAOut3BSWtVdm\nW6B8Hn6/L0HKXJW3/o2EFC3YlWAnG7/V98Z5QjqDCjcgaB211kW33sw4b6eJCWmv\nlIuT/ygoYE9IWgayBz2X/gIN4aMdwyPFhLh1J2VMfABeWBk1RTCfhxUDGCxbtut4\n7aKWo+6G7yM6U+3b1swoRhZXGo52IS7YSKjTlV1ZURUmTOhgMoCvJYKFKsJUQOjS\nEneCEDV77IKzqyEClikPwAN9ycYtMhBIgtHLp8NDTsnM0K+B1aIGodgCwrfPWSVM\nkrYI2fWdAgMBAAECggEAD/9TcuDo00QQmAivT0syAll+otPk4vnFKLg2nCHnaQ+1\nkILB65Km87xau9SX9AzuJbrzX4QPDPy91AeR6a+6ubXNDjOa0kbz1Sq1J53bSBSj\n8W+WOkeGMWmliqhrRXIFDlF4ZFsy8KZoSx8viTLCuiJjaVxfq+xmpblCH4ZQhtYJ\noAzP1SPoUglBOd/XfcbVfmbdNxYsJHhF/9iIHGQ18usTW7mLYofkjxrqVtLBPs9G\njwKxfY7FD8AtE385AvEjj5JjuxIuCd4/MwHapywNqzyQUF6vfYQOg4BJaXIEbvFB\nw+QBqmMYU8ieb7fKlD1pUTgKjtnG3jFcc39JB6SgVwKBgQDcGlzOF0GCaMNhGMry\n9UfE/BwaBm04FwB3T3QGulh4kj8yHD2XW9xdJ9UGwaJGtCMkld7W9ypHAosug39B\nblQsfTneZw73UY/ddJfSdpFqJLQ/qIuCjABA04bTb74bvcJgeCdubrqTHHmWRew+\npV0YSL6pUT26NYy5m+dr6bPxSwKBgQC17u9Qv+CZCs+ChnXuokppIKnruuabBWOc\nUbZDgAELYz2r/iQfOrOZHIjqZGe4ZDk6UQhFPNS1zRJzIOkrzH0841/9XG04TYXw\naLmystGC0SXBLxpafPF1cFkB2Xknz5pwFJTZlGT1X+q3MLdl4QkVbxP8Egs3sjI5\nIDBIT2bLtwKBgQDaLNufglfyb+xz3AKYsOASeCFW/tXWyp4wpjaJ0L+PzNAN2QaI\neYtHYAt+5gP4d+l6A4FfrqNevju+wKQs9LNFYmAxgBDKwTONPlycR+G+yGFP1L9t\niV9a4xJ7lgFpOEFsJM5ZXjNdTdWMSwVx17MfNkSgS6KXaSt0dQEB7CftXwKBgCSk\nFYCu1D4eZkKEcBX6i3/2uyIlxzHreO9PqaSYkB1KBG6yRXYgrXElxRFn3VfOn5P2\nI/NF2BUxUwjq1OskSQjNRlTRm5GeU15iyRuLVhTBqJfqs6ULytl7IgH0WalB73mp\nO31CnL6qbawtXJJhKyIs99ppi+bQtbq5l9/IVgyrAoGAeCjQsqtwVaNhB2viSBWC\n5bWZMmW04r6bPt+HbeVOVC/dtNGW1payM5qx43P0LmkUMRtxJITqL9E4wWQau9vG\nCyT+Vpi3wDbOKL54fgRvIHW9xud2iwe6gE+9XiUmi/GiccWvRSnsHRwgSBLmoFkW\nutaf/qpCjv0ySSWcI5Nov/k=\n-----END PRIVATE KEY-----\n",
            "client_email": "incentive@incentiverfv.iam.gserviceaccount.com",
            "client_id": "114499612243481116353",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/incentive%40incentiverfv.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
      - key: API_USERNAME
        value: vtexappkey-lojatuddub2b-UNFLSV
      - key: API_PASSWORD
        value: DLUBEIGYLNLLOMBKCRJICLOVLNYJFUNFXLSOGNKHXYMAVKBBPNEMBKVRXYPQJXSQZGODTMDPGCKEYNABLXURPBEMPARHYTXAFWAPVYHCJPFZZRTJYOEMDAAYCBNTUWRN
      - key: MIRE_API_BASE_URL
        value: https://mire.omnni.com.br/api
      - key: MIRE_API_SELLER_ID
        value: 85efe66a-ccbc-11ee-b981-02001700e806
